### ISSUE TITLE
user Id creation are not unique (Important)

### ISSUE THREAD

**Issue by marcmueller86** [PanMig/Chemistry-Lab#16]
The creation of the user id does not work, in the pilot there were all user_ids equal. 
The  error has to be in the class `UserIdentification` in the Start() function: 

@PanMig please check if this receives the right values, when adding a name, class and school
`string[] user_ids = inputFields.OfType<InputField>().Select(o => o.ToString()).ToArray();`

In the SDK we have to check if this function is working correctly:
@Marc please check if the hashing is working correctly
`string hashed_user_id = GoedleUtils.userHash(user_ids.ToString());`

**Comment by PanMig** [comment]
Marc,
 
The user_ids array does not have the right values. It seems that you are getting the title of the input field object (it returns name, class ,school). What you need is to get the value of the TEXT child of the input field. I tried to do it but I cannot really understand this line of code. The question is however, do we really need this complex behaviour because you can get the values through the game manager, that works and then parse them for md5 format ?

**Comment by marcmueller86** [comment]
Thank you for the hint! I already start changing it.
