### ISSUE TITLE
Can not insert the carbon in CH4

### ISSUE THREAD

**Issue by jimver04** [PanMig/Chemistry-Lab#18]
Pano

I can not insert the carbon in CH4. Also it is buggy in other molecules. It seems that the raycasting is not working properly. Raycasting returns a vector of how many meshes were intersected. Cylinders are also raycasted?  Meshes that have normals pointed to the same direction with the beam are usually neglected in raycasting. 
Also if I press multiple times a button of an atom, it puts multiple atoms one behind the other. Make it to place it below one each other.

Handling is much better. 

![image](https://user-images.githubusercontent.com/1898502/39686087-a8c2af84-51cf-11e8-9dab-66872a0ae89f.png)

**Comment by PanMig** [comment]
You cannot place it because you are not allowed to. This is ammonia as stated below and not methane. If you read the molecule in the bar below you will see that it prints ammonia. Raycasting has to do with sending rays mostly through mouse click, in this we have collision that is enabled when an object's collider touches another collider.

**Comment by PanMig** [comment]
Also, the suggestion about placing the molecules below one each other will create a huge problem in case the user presses the button many times, the screen will be populated with atoms. Two choices are available, either the one that I have at the moment or limit only one atom every time (too time consuming).
